services:
  web:
    image: busybox:latest
    container_name: fabrica-games-dev
    # O volume é o que permite você editar o código e ver a mudança na hora
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    command: >
      /bin/sh -c "
      echo 'Servidor de DEV rodando em http://localhost:8080' &&
      busybox httpd -f -vv -p 80 -h /var/www/html
      "